# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sejin blog
tagline:          '$신입 개발자'
description:      '                                                                                                Made by <a href="https://twitter.com/nas_9111" target="_blank">@nas_9111</a>.'
url:              http://sjra119.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
